//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLibrary.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbLibraryEntities : DbContext
    {
        public DbLibraryEntities()
            : base("name=DbLibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblBooks> tblBooks { get; set; }
        public virtual DbSet<tblCase> tblCase { get; set; }
        public virtual DbSet<tblCategories> tblCategories { get; set; }
        public virtual DbSet<tblMembers> tblMembers { get; set; }
        public virtual DbSet<tblMovements> tblMovements { get; set; }
        public virtual DbSet<tblPunishments> tblPunishments { get; set; }
        public virtual DbSet<tblWorkers> tblWorkers { get; set; }
        public virtual DbSet<tblWriters> tblWriters { get; set; }
    }
}
