//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLibrary.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblWriters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblWriters()
        {
            this.tblBooks = new HashSet<tblBooks>();
        }

        public int WriterId { get; set; }

        [Required(ErrorMessage = "Yazar Adýný Boþ Geçemezsiniz.")]
        public string WriterName { get; set; }

        [StringLength(20, ErrorMessage = "Soyad 20 Karakterden Uzun Olamaz.")]
        public string WriterSurname { get; set; }

        public string WriterDetail { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBooks> tblBooks { get; set; }
    }
}
